#!/bin/bash
files=$(git diff --cached --name-only | grep '\.js$')

# Prevent ESLint help message if no files matched
if [[ $files = "" ]] ; then
    exit 0
fi

failed=0
for file in ${files}; do
    git show :$file | ./node_modules/.bin/eslint --fix $file
    if [[ $? != 0 ]] ; then
        failed=1
    fi
done;

if [[ $failed != 0 ]] ; then
    echo -e "\033[31m 禁止提交：请修复你的语法错误！ \033[0m"
    exit $failed
fi
